### ISSUE TITLE
Which channel ID and PAN ID use for network creation ?

### ISSUE THREAD

**Issue by krunalchauhan637** [SiliconLabs/wisun-br-linux-docker#1]
I have run successfully this setup.
Router is alos connected with Border Router

I want to know how channel & Pan ID assign ?
How can I set channel and pand 
![Router](https://user-images.githubusercontent.com/59273222/162433197-edcd24db-e108-47fb-9f22-7f7f2d9a8b8a.PNG)
![Border_Router](https://user-images.githubusercontent.com/59273222/162433207-fb970e83-d6f4-4971-a388-9f4c721937af.PNG)

?

**Comment by silabs-JulienT** [comment]
Hi,

I recommend moving directly to the wsbrd daemon outside of the docker using [this repository](https://github.com/SiliconLabs/wisun-br-linux). You can edit the examples/wsbrd.conf file to change the PHY configuration (edit the regulatory domain, operating class, operating mode). You can also force the PAN ID to a specific ID by editing pan_id. 

If you want to remain on the Docker solution, you can check out the help using the command below:
`docker run -ti --privileged --rm wisun-img --help`
