### ISSUE TITLE
Possible execute wisun border router wihtout docker ? 

### ISSUE THREAD

**Issue by krunalchauhan637** [SiliconLabs/wisun-br-linux-docker#2]
I have check with raspberry board it is working fine.
Now for production we are planning with rugged board RB-i.MX 6UL (replacement of raspberry ).
Is it possible to run wisun border router wihtout docker in RB-i.MX 6UL board

**Comment by jerome-pouiller** [comment]
Sure. The docker image is only an example of how to configure the network.

**Comment by silabs-JulienT** [comment]
You can refer to the [wisun-br-linux](https://github.com/SiliconLabs/wisun-br-linux) repository.
