### ISSUE TITLE
WISUN NODE PACKET SENDING

### ISSUE THREAD

**Issue by HdSls** [SiliconLabs/wisun-br-linux-docker#4]
Now I am using Wisun SOC CLI and Rpi Border Router. Now when I ping from Tera term to border router I get ICMP eco request. So now I want to send string or packet in the  way from Wisun node to BR and we can see packet in wsbrb. So how we can do this ....

**Comment by chenek** [comment]
You can follow the steps in https://community.silabs.com/s/article/KBA-Wi-SUN-SoC-CLI-sending-UDP-data-to-Linux-Border-Router?language=en_US to do this.

**Comment by HdSls** [comment]
I had try to do that but that was not happening,
https://community.silabs.com/s/question/0D58Y0000908MoHSAU/i-am-using-wisun-soc-cli-now-in-that-i-want-to-send-stringpayload-from-node-to-border-router-so-how-i-can-do-communication-between-node-and-border-router-via-wisun-border-router-repo-link-httpsgithubcomsiliconlabswisunbrlinuxdocker 


please refer this in that I had done all the things but not getting results

**Comment by silabs-JulienT** [comment]
Please refer to Section 4 of the AN1332 document:
https://www.silabs.com/documents/public/application-notes/an1332-wi-sun-network-configuration.pdf
