### ISSUE TITLE
Updating crates.io index

### ISSUE THREAD

**Issue by Memphisvanss** [SiliconLabs/wisun-br-linux-docker#5]
Hi, 

I have this issue when I tried to build the container

Is on a raspberry pi facing directly to internet with an ip public

Can anybody help me? please!

warning: spurious network error (2 tries remaining): bad packet length; class=Net (12)
#36 46.12 error: failed to get `clap` as a dependency of package `wsbrd_cli v0.1.0 (/usr/src/wsbrd/app_wsbrd_cli)`
#36 46.12
#36 46.12 Caused by:
#36 46.12   failed to load source for dependency `clap`
#36 46.12
#36 46.12 Caused by:
#36 46.12   Unable to update registry `https://github.com/rust-lang/crates.io-index`
#36 46.12
#36 46.12 Caused by:
#36 46.12   failed to fetch `https://github.com/rust-lang/crates.io-index`
#36 46.12
#36 46.12 Caused by:
#36 46.12   error reading from the zlib stream; class=Zlib (5)
#36 46.17 ninja: job failed: cd /usr/src/wsbrd-build && /usr/bin/cargo build --target=aarch64-alpine-linux-musl --target-dir=cargo/ --manifest-path=/usr/src/wsbrd/app_wsbrd_cli/Cargo.toml && /usr/bin/cmake -E copy cargo/aarch64-alpine-linux-musl/debug/wsbrd_cli wsbrd_cli
#36 47.11 ninja: subcommand failed
------
executor failed running [/bin/sh -c ./wsbrd-install.sh]: exit code: 1

**Comment by jerome-pouiller** [comment]
The release 2.6.1 fixes that issue.

The tag has been pushed on github a few weeks ago. However, I have forgotten to update the `main` branch. It is fixed now.
