### ISSUE TITLE
Error occurred while building image

### ISSUE THREAD

**Issue by LZHHZLLZH** [SiliconLabs/wisun-br-linux-docker#6]
When I execute 
DOCKER_BUILDKIT=1 docker build --build-arg "GIT_DESCRIBE=$(git describe --tag --match v*)" -t wisun-img .
to make the image, error occured like below:

#36 119.5 [1/151] Generating wsbrd_cli
#36 119.8     Updating crates.io index
#36 122.9 error: failed to get `clap` as a dependency of package `wsbrd_cli v0.1.0 (/usr/src/wsbrd/app_wsbrd_cli)`
#36 122.9
#36 122.9 Caused by:
#36 122.9   failed to load source for dependency `clap`
#36 122.9
#36 122.9 Caused by:
#36 122.9   Unable to update registry `https://github.com/rust-lang/crates.io-index`
#36 122.9
#36 122.9 Caused by:
#36 122.9   failed to fetch `https://github.com/rust-lang/crates.io-index`
#36 122.9
#36 122.9 Caused by:
#36 122.9   error reading from the zlib stream; class=Zlib (5)
#36 122.9 ninja: job failed: cd /usr/src/wsbrd-build && /usr/bin/cargo build --target=x86_64-alpine-linux-musl --target-dir=cargo/ --manifest-path=/usr/src/wsbrd/app_wsbrd_cli/Cargo.toml && /usr/bin/cmake -E copy cargo/x86_64-alpine-linux-musl/debug/wsbrd_cli wsbrd_cli
#36 123.1 ninja: subcommand failed
------
executor failed running [/bin/sh -c ./wsbrd-install.sh]: exit code: 1

How can I solve this problem

**Comment by jerome-pouiller** [comment]
Hi, this issue should have been fixed on release. 2.6.1. Can you you you are using the last version of `wisun-br-linux-docker`?

**Comment by LZHHZLLZH** [comment]
> Hi, this issue should have been fixed on release. 2.6.1. Can you you you are using the last version of `wisun-br-linux-docker`?

As you said, after I downloaded the latest code and rebuilt the image, the problem was solved. Thanks.
